#pragma config(Sensor, in8,    Lift1_R,        sensorPotentiometer)
#pragma config(Motor,  port1,           LiftR,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftL,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define abs(X) ((X < 0) ? -1 * X : X)
#define M_PI acos(-1.0)

float wheelRadiusCM = 10.16;

//define functions
int getStraightGoal(float cm);
int getRotationGoal(float deg);
void moveArm(float deg, int armSpeed);

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
	const short leftButton   = 1;
const short centerButton = 2;
const short rightButton  = 4;
/////////////Button commands////////////////////////
/////////////Wait for press////////////////////////
void waitForPress()
{
	while(nLCDButtons == 0) {}
	wait1Msec(5);
}
/////////////Wait for press//////////////////////////
/////////////Wait for release////////////////////////
void waitForRelease()
{
	while(nLCDButtons !=0) {}
	wait1Msec(5);
}

void pre_auton()
{
		//Declare count variable to keep track of our choice
	int count = 0;

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Autonomous 1");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Autonomous 2");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Autonomous 3");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Autonomous 4");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:
			count = 0;
			break;
		}
	}
	//------------- End of User Interface Code ---------------------

	//------------- Beginning of Robot Movement Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Autonomous 1");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(2000);						// Robot waits for 2000 milliseconds

		// Move forward at full power for 3 seconds
		motor[rightMotor] = 127;			// Motor on port2 is run at full (127) power forward
		motor[leftMotor]	= 127;			// Motor on port3 is run at full (127) power forward
		wait1Msec(3000);							// Robot runs previous code for 3000 milliseconds before moving on
		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Autonomous 2");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(2000);						// Robot waits for 2000 milliseconds

		// Move reverse at full power for 3 seconds
		motor[rightMotor] = -127;			// Motor on port2 is run at full (-127) power reverse
		motor[leftMotor]	= -127;			// Motor on port3 is run at full (-127) power reverse
		wait1Msec(3000);							// Robot runs previous code for 3000 milliseconds before moving on
		break;
	case 2:
		//If count = 2, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Autonomous 3");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(2000);						// Robot waits for 2000 milliseconds

		//Turn right for 3 seconds
		motor[rightMotor] = -63;			// Motor on port2 is run at half power reverse
		motor[leftMotor]	= 63;				// Motor on port3 is run at half power forward
		wait1Msec(3000);							// Robot runs previous code for 3000 milliseconds before moving on
		break;
	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Autonomous 4");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(2000);						// Robot waits for 2000 milliseconds

		//Turn left for 3 seconds
		motor[rightMotor] = 63;				// Motor on port2 is run at half power forward
		motor[leftMotor]	= -63;			// Motor on port3 is run at half power reverse
		wait1Msec(3000);							// Robot runs previous code for 3000 milliseconds before moving on
		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}
	//------------- End of Robot Movement Code -----------------------
}
}


task autonomous()
{
	motor[Left]= -127;
	motor[Right]= -127;
	wait1Msec(950);
	motor[Left]= 0;
	motor[Right]= 0;
// The robot goes backward to the ramp

	motor[Left]= -127;
	motor[Right]= 127;
	wait1Msec(500);
	motor[Left]= 0;
	motor[Right]= 0;
// The robot turns around

	motor[Left]= -127;
	motor[Right]= -127;
	wait1Msec(7000);
	motor[Left]= 0;
	motor[Right]= 0;
// The robot goes backward to go up the ramp
}

task usercontrol()
{
	while (true)
		{
 			int ClawR = vexRT(Btn8D);
 			int ClawL = vexRT(Btn8R);
 			int LiftUp = vexRT(Btn5D);
 			int LiftDown = vexRT(Btn5U);
 			int LiftUp2 = vexRT(Btn6U);
 			int LiftDown2 = vexRT(Btn6D);
 			int IntakeForward = vexRT(Btn7U);
 			int IntakeBackward = vexRT(Btn7D);
 			int leftstickX;
 			int leftstickY;
 			int deadzone = 5;

 //////////////////Arcade Drive/////////////////
	if (abs(vexRT[Ch3]) > deadzone)
		{leftstickY = vexRT[Ch3];}

	else
		{leftstickY = 0;}

	if (abs(vexRT[Ch4]) > deadzone)
		{leftstickX = vexRT[Ch4];}

	else
		{leftstickX =0 ;}

	motor[Left] = leftstickY - leftstickX;
	motor[Right]= leftstickY + leftstickX;
/////////////////Arcade Drive///////////////////////

//////////////////Lift//////////////////////////////
	if (LiftUp == 1)
		{
			motor[LiftR] = 127;
			motor[LiftL] = 127;
		}

	else if (LiftDown == 1)
		{
			motor[LiftR] = -127;
			motor[LiftL] = -127;
		}

	else
		{
			motor[LiftR] = 0;
			motor[LiftL] = 0;
		}
//////////////////Lift///////////////////////////////

/////////////////Second Lift/////////////////////////
	if (LiftUp2 == 1)
		{
			motor[Lift2] = 127;
		}
	else if (LiftDown2 == 1)
		{
			motor[Lift2] = -127;
		}
	else
		{
			motor[Lift2] = 0;
		}
/////////////////Second Lift//////////////////////////

/////////////////Intake//////////////////////////////
	if (IntakeForward == 1)
		{
			motor[Intake] = 127;
		}
	else if (IntakeBackward == 1)
		{
			motor[Intake] = -127;
		}
	else
		{
			motor[Intake] = 0;
		}
/////////////////Intake//////////////////////////////

//////////////////Claw///////////////////////////////
	if (ClawR == 1)
		{motor [Claw] = -97;}

	else if (ClawL == 1)
		{motor [Claw] = 97;}

	else
		{motor [Claw] = 0;}
//////////////////Claw///////////////////////////////

    UserControlCodePlaceholderForTesting();
  }
}

///////////////Functions////////////////////////
	int getStraightGoal(float cm)
		{return 392*(cm/(wheelRadiusCM*M_PI));}

	int getRotationGoal(float deg)
		{return 392*(deg/102.9);}

void moveArm(float deg, int armSpeed)
{
	armSpeed = abs(armSpeed);

		if(deg < SensorValue[LiftR])
		{
			while(SensorValue[LiftR] <= deg)
			{motor[LiftR] = motor[LiftL] = armSpeed;}
		}

		else
		{
			while(SensorValue[LiftR] >= deg)
			{motor[LiftR] = motor[LiftL] = -armSpeed;}
		}
}
/////////////End of Functions///////////////////
