#pragma config(Motor,  port2,           Right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Lift,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  while (true)
  {
  	int leftside = vexRT(Ch3);
		int rightside = vexRT(Ch2);
		int liftup = vexRT(Btn6U);
		int liftdown = vexRT(Btn6D);
		int clawopen = vexRT(Btn5U);
		int clawclose = vexRT(Btn5D);

		if (leftside >=10)
			{motor [Left] =leftside;}
		else if (leftside <=-10)
			{motor [Left] =leftside;}
		else
			{motor [Left] =0;}
// Leftside of the drivetrain

		if (rightside >=10)
			{motor [Right] =rightside;}
		else if (rightside <=-10)
			{motor [Right] =rightside;}
		else
			{motor [Right] =0;}
// Rightside of the drivetrain

		if (liftup == 1)
		{
			motor [Lift] = 127;
		}
// Lift to go up

		else if (liftdown == 1)
		{
			motor [Lift] = -127;
		}
// Lift to go down

		else
		{
			motor [Lift] = 10;
		}
// If the Lift button isn't pressed then it won't move

		if (clawopen == 1)
	  	motor [Claw] = 127;
// Opens the claw
	 	else if (clawclose == 1)
	 	  motor [Claw] = -127;
// Closes the claw
	 	else
	 		{motor [Claw] = 0;}
// If the claw button isn't pressed then there will be no claw movement

    UserControlCodePlaceholderForTesting();
  }
}
